language: node_js
node_js:
  - 11
stages:
  - lint
  - test
  - integration
  - e2e
  - deploy
branches:
  except:
    - gh-pages
    - l10n_develop
service :
  - docker

env :
  - DOCKER_IMAGE_NAME=938788377650.dkr.ecr.eu-west-1.amazonaws.com/juice-shop:1.0-$TRAVIS_BUILD_NUMBER

install: if [ -z "$TRAVIS_TAG" ]; then npm install; fi
script: if [ -z "$TRAVIS_TAG" ]; then NODE_ENV=test npm test; fi
before_deploy:
  - rm -rf node_modules
  - rm -rf frontend/node_modules
  - npm install --production
  - npm run package
jobs:
  include:
    - stage: lint
      if: tag IS blank
      install: npm i -g standard && cd frontend && npm install && cd ..
      script: npm run lint
    - stage: integration
      if: tag IS blank
      script:
        - export NODE_ENV=test
        - npm test
        - npm run frisby
      after_success:
        - "./node_modules/.bin/lcov-result-merger 'build/reports/coverage/**/lcov.info' 'build/reports/coverage/lcov_merged.info'"
        - "./node_modules/.bin/codeclimate-test-reporter < ./build/reports/coverage/lcov_merged.info"
    - stage: e2e
      if: tag IS blank
      script:
        - export NODE_ENV=test
        - npm run protractor
after_success :
   - pip install --user awscli
   - docker build  -t william/juice-shop .
   - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
   - docker tag william/juice-show $DOCKER_IMAGE_NAME
   - docker push $DOCKER_IMAGE_NAME
   - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name hellonode --region eu-west-1 --parameter-override ImageName=$DOCKER_IMAGE_NAME
   - aws cloudformation update-stack --stack-name hellonode --template-body file://ecs-task.yaml --region eu-west-1 --parameters "ParameterKey=ImageName,ParameterValue=$DOCKER_IMAGE_NAME"
