language: node_js
node_js:
  - 11
stages:
#  - lint
#  - test
#  - integration
#  - e2e
  - deploy
dist: trusty

branches:
  except:
    - gh-pages
    - l10n_develop
service :
  - docker
addons :
  sonar_cloud:
    organization: "william-billaud-github"
env :
  - DOCKER_IMAGE_NAME=938788377650.dkr.ecr.eu-west-1.amazonaws.com/juice-shop:1.0-$TRAVIS_BUILD_NUMBER

#before_deploy:
#  - rm -rf node_modules
#  - rm -rf frontend/node_modules
#  - npm install --production
#  - npm run package
#
#
script:
  - sonar-scanner 


after_success:
#  - rm -rf node_modules
#  - rm -rf frontend/node_modules
#  - npm install --production
#  - npm run package
  - pip install --user awscli
  - docker build  -t $DOCKER_IMAGE_NAME .
  - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
  - docker push $DOCKER_IMAGE_NAME
  - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name juice-shop --region eu-west-1 --parameter-override ImageName=$DOCKER_IMAGE_NAME
  - aws cloudformation update-stack --stack-name juice-shop --template-body file://ecs-task.yaml --region eu-west-1 --parameters "ParameterKey=ImageName,ParameterValue=$DOCKER_IMAGE_NAME"
